### ISSUE TITLE
OCS Tag import as Inventory number

### ISSUE THREAD

**Issue by Tyjex** [pluginsGLPI/ocsinventoryng#180]
Versions:
Plugin 1.5.3
GLPI 9.3
OCS Server 2.5

I setup a OCS Server and a GLPI server on the same VM openSUSE Leap 15 then I got some PCs setup with the OCS Agent to get data into my OCS DB worked perfectly fine I also sent a TAG which I wanted to use as a inventory number for GLPI. 

I configured the connection to OCS in GLPI with the plugin and also set the OCS Tag to be imported as a inventory number (under Tools -> OCS -> Server setup -> OCSNG administrative information). Then I synchronized GLPI with OCS which worked fine except the Tag didnt fill in the inventory number field, it only works when I press force full import.

I looked arround google and the GLPI forum but couldnt figure out if it was a bug or some other problem.

**Comment by amma35** [comment]
We have just performed the test with the inventory number, it is correctly imported during synchronization. 

Attention during synchronization, it is necessary that the agent is made a modification in the OCS machine otherwise GLPI will not detect any changes and therefore will not make any modifications in GLPI.

Normally, the machines where there is a modification, the TAG must be imported in GLPI.

**Comment by general2000vn** [comment]
I have the same issue, GLPI ver 9.3.1, OCS ver 2.5, GLPI OCS plugin ver 1.5.4.

Computer imported manually, not automatically via automatic actions.
And Inventory number is NOT imported, only the field OCS Inventory Tag of the plugin.

Any suggestion? Thank you very much.

**Comment by tsmr** [comment]
Ok into last version
